global:
  name: RISC-V Ecosystem Interactive Landscape
  short_name: RISC-V
  repo: riscv-admin/riscv-landscape
  website: https://landscape.riscv.org
  short_domain: l.riscv.org
  company_url: https://riscv.org/
  email: info@riscv.org
  self: https://www.crunchbase.com/organization/linux-foundation
  slack_channel: T08PSQ7BQ/BM7M5TKSR/Xjll8jWb2cgpO7aOCGxUtebU
  meta:
    title: RISC-V Landscape
    fb_admin: alex.contini.94
    description: Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets
    twitter: "@todogroup"
    google_site_verification: u_xqWIf8_EzRP4UF92px16rTSoIP49D_g9i7M-4rXds
    ms_validate: 3AF9FFA12CCC3C49C0ABA71CCA222665
  membership: risc-v-members
  flags:
    companies: risc-v-members
twitter:
  search: riscv.cncf.io
  url: https://landscape.riscv.org
  text: RISC-V Landscape
relation:
  label: RISC-V Relation
  url: riscv
  values:
    - id: company
      label: risc-v-members
      tag: Company
      big_picture_order: 3
      children: [] # Add an empty children field here
    - id: member
      label: RISC-V Member Products/Projects
      tag: RISC-V Member
    - id: false
      label: Non-RISC-V Member Products/Projects
      url: "no"
membership:
  Premier:
    name: Premier
    label: Premier Member
    funding: Premier
  Strategic:
    name: Strategic
    label: Strategic Member
    funding: Strategic
  Community:
    name: Community
    label: Community Member
    funding: Community
  linux_foundation:
    name: LF
    label: Project
    funding: Linux Foundation
    crunchbase_and_children: https://www.crunchbase.com/organization/linux-foundation
  "false":
    funding: "No"
home:
  header: >
    <h1>RISC-V Landscape</h1> The RISC-V landscape (<a target="_blank" href="images/landscape.png">png</a>, <a target="_blank"
    href="images/landscape.pdf">pdf</a>) is dynamically generated below. It is modeled after the <a href="http://landscape.cncf.io">CNCF landscape</a> and based
    on the same open source code.
  footer: |
    Crunchbase data is used under license from Crunchbase to CNCF.
presets:
  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
    label: Open source cards by age
  - url: /license=apache-license-2-0
    label: Apache-2.0 landscape
  - url: /format=card-mode&grouping=category
    label: Cards in categories
  - url: /format=card-mode&grouping=no&sort=stars
    label: Cards by stars
  - url: /format=card-mode&grouping=headquarters
    label: Group by location
  - url: /format=card-mode&grouping=no&sort=amount
    label: Cards by MCap/Funding
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    title: RISC-V Landscape
    fullscreen_header: See the interactive landscape at l.riscv.org
    elements:
      - type: VerticalCategory
        category: risc-v-members
        width: 300
        height: 200
        top: 0
        left: 0
        color: rgb(103,66,18)
        fit_width: false
test:
  header: RISC-V Landscape
  section: risc-v-members
  logo: google-llc.svg
prerender:
  members: /card-mode?category=risc-v-members&grouping=category&embed=yes&style=borderless
export: {}
