name: New Landscape Entry
description: New entry for the Landscape
title: New Landscape Entry - [PROJECT]
labels: ['new landscape entry']
assignees: 
  - bprestonlf
  - rpsene
body:
  - type: markdown
    attributes:
      value: "Thank you for expressing interest in including your project within the RISC-V Ecosystem Landscape. To proceed with adding your project, kindly fill out the form provided below. Your contribution will be a valuable addition to the RISC-V Ecosystem Landscape."
  - type: input
    id: name
    attributes:
      label: Project Name
      description: Also update `[PROJECT]` in the title above
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
  - type: input
    id: webpage
    attributes:
      label: Homepage URL
    validations:
      required: true
  - type: input
    id: crunchbase
    attributes:
      label: Crunchbase URL (https://www.crunchbase.com/)
    validations:
      required: true
  - type: input
    id: repo_url
    attributes:
      label: Repository URL
    validations:
      required: true
  - type: input
    id: organization
    attributes:
      label: Organization hosting or owning the project
    validations:
      required: true
  - type: textarea
    id: ecosystem
    attributes:
      label: Evidence of RISC-V ecosystem support
      description: Concrete examples, such as use cases, community discussions, papers, etc.
    validations:
      required: true
  - type: textarea
    id: logo
    attributes:
      label: Logo
      description: Logo preferably should be in SVG, EPS, or AI format
      placeholder: Drag and drop logo here or provide link to the logo
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Pick the best category for your project
      options:
          - Applications
          - Boot
          - Compilers
          - Design Tools
          - Developer Boards
          - Hypervisor
          - Implementations
          - Infrastructure
          - Libraries
          - Operating Systems
          - Processors
          - Runtimes
          - Services
    validations:
      required: true
