name: Update Landscape Entry
description: Let us know if a landscape entry needs corrected.
title: Update Landscape Entry for [PROJECT]
labels: ['update entry']
assignees: 
  - rpsene
body:
  - type: markdown
    attributes:
      value: Kindly replace [PROJECT] in the title above with the actual name of your project. Once you have done this, please provide a detailed description of the required changes in the space below.
  - type: textarea
    attributes:
      label: Changes requested
    validations:
      required: true
